baseURL = "/"
title = "bulgariu.xyz"
theme = "hugo-coder"
uglyURLs = false
relativeURLs = true
languageCode = "en"

# Change this if you want spanish (es) or english (en) to show up first when someone touches your website
defaultContentLanguage = "es"
#paginate = 6
enableEmoji = true

[markup.highlight]
noClasses = false

[params]
author = "Raul Bulgariu Suciu"
description = "Raul's personal page."
keywords = "Cybersecurity, Linux, HackTheBox, HTB, Guides"
info = ["SysAdmin", "Ethical Hacker"]
avatarURL = "images/avatar.png"
dateFormat = "January 2, 2006"
since = 2023

# Right To Left, shift content direction for languages such as Arabic
rtl = false

# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "HTB"
icon = "fa fa-2x fa-cube"
weight = 1
url = "https://app.hackthebox.com/profile/1471024"

[[params.social]]
name = "Email"
icon = "fa fa-2x fa-envelope"
weight = 2
url = "mailto:raul@bulgariu.xyz"

[[params.social]]
name = "Git"
icon = "fa fa-2x fa-github"
weight = 3
url = "https://github.com/raul741"

[languages.en]
languageName = ":es:"
title = "bulgariu.xyz"

[[languages.en.menu.main]]
name = "CV"
weight = 1
url = "https://cv.bulgariu.xyz/en"

[[languages.en.menu.main]]
name = "Git"
weight = 2
url = "https://github.com/raul741"

[[languages.en.menu.main]]
name = "About"
weight = 3
url = "/about"

[[languages.en.menu.main]]
name = "Posts"
weight = 4
url = "/posts"

[[languages.en.menu.main]]
name = "Contact me"
weight = 6
url = "contact/"

[languages.es]
languageName = ":uk:"
title = "bulgariu.xyz"

[languages.es.params]
author = "Raúl Bulgariu Suciu"
info = ["SysAdmin", "Hacker Ético"]
description = "Página web personal de Raúl Bulgariu Suciu"
keywords = "Ciberseguridad, Linux, HackTheBox, HTB, Guías"

[[languages.es.menu.main]]
name = "CV"
weight = 1
url = "https://cv.bulgariu.xyz/es"

[[languages.es.menu.main]]
name = "Git"
weight = 2
url = "https://github.com/raul741"

[[languages.es.menu.main]]
name = "Sobre mí"
weight = 3
url = "about/"

[[languages.es.menu.main]]
name = "Publicaciones"
weight = 4
url = "posts/"

[[languages.es.menu.main]]
name = "Contacta conmigo"
weight = 6
url = "/contact"
